import { createFileRoute, Link } from "@tanstack/react-router";
import { Trash2, Minus, Plus, ArrowRight } from "lucide-react";
import { StoreLayout } from "@/components/store/StoreLayout";
import { OrderSummary } from "@/components/shared/OrderSummary";
import { Button } from "@/components/ui/button";
import { useCart } from "@/context/CartContext";
import { formatPrice } from "@/lib/format";

export const Route = createFileRoute("/cart")({ component: CartPage });
function CartPage() { const cart = useCart(); return <StoreLayout><div className="container-page py-10 md:py-16"><p className="eyebrow">Your selection</p><h1 className="mt-3 font-display text-4xl md:text-5xl">Shopping bag</h1>{cart.items.length === 0 ? <div className="border-y border-border py-20 text-center"><p className="text-muted-foreground">Your bag is waiting for something considered.</p><Button asChild className="mt-6"><Link to="/shop">Continue shopping</Link></Button></div> : <div className="mt-10 grid gap-10 lg:grid-cols-[1fr_360px]"><div className="divide-y divide-border border-y border-border">{cart.items.map((item) => <article key={item.id} className="flex gap-4 py-5"><img src={item.image} alt={item.name} className="size-28 object-cover sm:size-36" /><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><div><Link to="/product/$slug" params={{ slug: item.slug }} className="font-medium hover:underline">{item.name}</Link><p className="mt-1 text-xs text-muted-foreground">{item.color} · {item.size}</p></div><button aria-label={`Remove ${item.name}`} onClick={() => cart.remove(item.id)} className="text-muted-foreground hover:text-destructive"><Trash2 className="size-4" /></button></div><div className="mt-6 flex items-center justify-between"><div className="flex items-center border border-border"><button className="p-2" onClick={() => cart.setQuantity(item.id, item.quantity - 1)}><Minus className="size-3" /></button><span className="w-8 text-center text-sm">{item.quantity}</span><button className="p-2" onClick={() => cart.setQuantity(item.id, item.quantity + 1)}><Plus className="size-3" /></button></div><span className="font-medium">{formatPrice(item.price * item.quantity)}</span></div></div></article>)}</div><OrderSummary subtotal={cart.subtotal} discount={cart.discount} shipping={cart.shipping} total={cart.total} actionLabel="Proceed to checkout" actionTo="/checkout" /></div>}</div></StoreLayout>; }
